/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as tokenSol from "./Token.sol";
import type * as solmate from "./solmate";

export type { tokenSol };

export type { solmate };
export * as factories from "./factories";
export type { ERC20 } from "./solmate/ERC20";
export { ERC20__factory } from "./factories/solmate/ERC20__factory";
export type { Afonso } from "./Token.sol/Afonso";
export { Afonso__factory } from "./factories/Token.sol/Afonso__factory";
